#!/bin/bash
module load autodock/4.2.6
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1128.pdbqt --out docked/hsg1_dbfda1128.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1239.pdbqt --out docked/hsg1_dbfda1239.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1465.pdbqt --out docked/hsg1_dbfda1465.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1532.pdbqt --out docked/hsg1_dbfda1532.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1580.pdbqt --out docked/hsg1_dbfda1580.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1615.pdbqt --out docked/hsg1_dbfda1615.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1641.pdbqt --out docked/hsg1_dbfda1641.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda1652.pdbqt --out docked/hsg1_dbfda1652.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda375.pdbqt --out docked/hsg1_dbfda375.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda376.pdbqt --out docked/hsg1_dbfda376.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda377.pdbqt --out docked/hsg1_dbfda377.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda378.pdbqt --out docked/hsg1_dbfda378.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda379.pdbqt --out docked/hsg1_dbfda379.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda38.pdbqt --out docked/hsg1_dbfda38.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda380.pdbqt --out docked/hsg1_dbfda380.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda381.pdbqt --out docked/hsg1_dbfda381.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda382.pdbqt --out docked/hsg1_dbfda382.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda383.pdbqt --out docked/hsg1_dbfda383.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda384.pdbqt --out docked/hsg1_dbfda384.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda385.pdbqt --out docked/hsg1_dbfda385.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda386.pdbqt --out docked/hsg1_dbfda386.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda387.pdbqt --out docked/hsg1_dbfda387.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda388.pdbqt --out docked/hsg1_dbfda388.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda389.pdbqt --out docked/hsg1_dbfda389.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda39.pdbqt --out docked/hsg1_dbfda39.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda390.pdbqt --out docked/hsg1_dbfda390.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda391.pdbqt --out docked/hsg1_dbfda391.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda392.pdbqt --out docked/hsg1_dbfda392.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda393.pdbqt --out docked/hsg1_dbfda393.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda394.pdbqt --out docked/hsg1_dbfda394.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda395.pdbqt --out docked/hsg1_dbfda395.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda396.pdbqt --out docked/hsg1_dbfda396.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda397.pdbqt --out docked/hsg1_dbfda397.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda398.pdbqt --out docked/hsg1_dbfda398.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda399.pdbqt --out docked/hsg1_dbfda399.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda4.pdbqt --out docked/hsg1_dbfda4.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda40.pdbqt --out docked/hsg1_dbfda40.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda400.pdbqt --out docked/hsg1_dbfda400.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda401.pdbqt --out docked/hsg1_dbfda401.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda402.pdbqt --out docked/hsg1_dbfda402.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda403.pdbqt --out docked/hsg1_dbfda403.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda404.pdbqt --out docked/hsg1_dbfda404.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda405.pdbqt --out docked/hsg1_dbfda405.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda406.pdbqt --out docked/hsg1_dbfda406.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda407.pdbqt --out docked/hsg1_dbfda407.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda408.pdbqt --out docked/hsg1_dbfda408.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda409.pdbqt --out docked/hsg1_dbfda409.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda41.pdbqt --out docked/hsg1_dbfda41.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda410.pdbqt --out docked/hsg1_dbfda410.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda411.pdbqt --out docked/hsg1_dbfda411.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda412.pdbqt --out docked/hsg1_dbfda412.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda413.pdbqt --out docked/hsg1_dbfda413.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda414.pdbqt --out docked/hsg1_dbfda414.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda415.pdbqt --out docked/hsg1_dbfda415.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda416.pdbqt --out docked/hsg1_dbfda416.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda417.pdbqt --out docked/hsg1_dbfda417.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda418.pdbqt --out docked/hsg1_dbfda418.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda419.pdbqt --out docked/hsg1_dbfda419.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda42.pdbqt --out docked/hsg1_dbfda42.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda420.pdbqt --out docked/hsg1_dbfda420.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda421.pdbqt --out docked/hsg1_dbfda421.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda422.pdbqt --out docked/hsg1_dbfda422.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda423.pdbqt --out docked/hsg1_dbfda423.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda424.pdbqt --out docked/hsg1_dbfda424.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda425.pdbqt --out docked/hsg1_dbfda425.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda426.pdbqt --out docked/hsg1_dbfda426.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda427.pdbqt --out docked/hsg1_dbfda427.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda428.pdbqt --out docked/hsg1_dbfda428.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda429.pdbqt --out docked/hsg1_dbfda429.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda43.pdbqt --out docked/hsg1_dbfda43.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda430.pdbqt --out docked/hsg1_dbfda430.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda431.pdbqt --out docked/hsg1_dbfda431.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda432.pdbqt --out docked/hsg1_dbfda432.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda433.pdbqt --out docked/hsg1_dbfda433.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda434.pdbqt --out docked/hsg1_dbfda434.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda435.pdbqt --out docked/hsg1_dbfda435.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda436.pdbqt --out docked/hsg1_dbfda436.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda437.pdbqt --out docked/hsg1_dbfda437.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda438.pdbqt --out docked/hsg1_dbfda438.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda439.pdbqt --out docked/hsg1_dbfda439.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda44.pdbqt --out docked/hsg1_dbfda44.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda440.pdbqt --out docked/hsg1_dbfda440.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda441.pdbqt --out docked/hsg1_dbfda441.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda442.pdbqt --out docked/hsg1_dbfda442.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda443.pdbqt --out docked/hsg1_dbfda443.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda444.pdbqt --out docked/hsg1_dbfda444.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda445.pdbqt --out docked/hsg1_dbfda445.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda446.pdbqt --out docked/hsg1_dbfda446.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda447.pdbqt --out docked/hsg1_dbfda447.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda448.pdbqt --out docked/hsg1_dbfda448.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda449.pdbqt --out docked/hsg1_dbfda449.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda45.pdbqt --out docked/hsg1_dbfda45.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda450.pdbqt --out docked/hsg1_dbfda450.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda451.pdbqt --out docked/hsg1_dbfda451.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda452.pdbqt --out docked/hsg1_dbfda452.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda453.pdbqt --out docked/hsg1_dbfda453.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda454.pdbqt --out docked/hsg1_dbfda454.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda455.pdbqt --out docked/hsg1_dbfda455.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda456.pdbqt --out docked/hsg1_dbfda456.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda457.pdbqt --out docked/hsg1_dbfda457.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda458.pdbqt --out docked/hsg1_dbfda458.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda459.pdbqt --out docked/hsg1_dbfda459.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda46.pdbqt --out docked/hsg1_dbfda46.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda460.pdbqt --out docked/hsg1_dbfda460.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda461.pdbqt --out docked/hsg1_dbfda461.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda462.pdbqt --out docked/hsg1_dbfda462.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda463.pdbqt --out docked/hsg1_dbfda463.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda464.pdbqt --out docked/hsg1_dbfda464.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda465.pdbqt --out docked/hsg1_dbfda465.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda466.pdbqt --out docked/hsg1_dbfda466.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda467.pdbqt --out docked/hsg1_dbfda467.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda468.pdbqt --out docked/hsg1_dbfda468.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda469.pdbqt --out docked/hsg1_dbfda469.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda47.pdbqt --out docked/hsg1_dbfda47.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda470.pdbqt --out docked/hsg1_dbfda470.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda471.pdbqt --out docked/hsg1_dbfda471.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda472.pdbqt --out docked/hsg1_dbfda472.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda473.pdbqt --out docked/hsg1_dbfda473.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda474.pdbqt --out docked/hsg1_dbfda474.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda475.pdbqt --out docked/hsg1_dbfda475.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda476.pdbqt --out docked/hsg1_dbfda476.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda477.pdbqt --out docked/hsg1_dbfda477.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda478.pdbqt --out docked/hsg1_dbfda478.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda479.pdbqt --out docked/hsg1_dbfda479.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda48.pdbqt --out docked/hsg1_dbfda48.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda480.pdbqt --out docked/hsg1_dbfda480.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda481.pdbqt --out docked/hsg1_dbfda481.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda482.pdbqt --out docked/hsg1_dbfda482.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda483.pdbqt --out docked/hsg1_dbfda483.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda484.pdbqt --out docked/hsg1_dbfda484.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda485.pdbqt --out docked/hsg1_dbfda485.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda486.pdbqt --out docked/hsg1_dbfda486.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda487.pdbqt --out docked/hsg1_dbfda487.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda488.pdbqt --out docked/hsg1_dbfda488.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda489.pdbqt --out docked/hsg1_dbfda489.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda49.pdbqt --out docked/hsg1_dbfda49.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda490.pdbqt --out docked/hsg1_dbfda490.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda491.pdbqt --out docked/hsg1_dbfda491.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda492.pdbqt --out docked/hsg1_dbfda492.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda493.pdbqt --out docked/hsg1_dbfda493.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda494.pdbqt --out docked/hsg1_dbfda494.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda495.pdbqt --out docked/hsg1_dbfda495.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda496.pdbqt --out docked/hsg1_dbfda496.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda497.pdbqt --out docked/hsg1_dbfda497.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda498.pdbqt --out docked/hsg1_dbfda498.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda499.pdbqt --out docked/hsg1_dbfda499.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda5.pdbqt --out docked/hsg1_dbfda5.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda50.pdbqt --out docked/hsg1_dbfda50.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda500.pdbqt --out docked/hsg1_dbfda500.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda501.pdbqt --out docked/hsg1_dbfda501.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda502.pdbqt --out docked/hsg1_dbfda502.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda503.pdbqt --out docked/hsg1_dbfda503.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda504.pdbqt --out docked/hsg1_dbfda504.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda505.pdbqt --out docked/hsg1_dbfda505.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda506.pdbqt --out docked/hsg1_dbfda506.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda507.pdbqt --out docked/hsg1_dbfda507.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda508.pdbqt --out docked/hsg1_dbfda508.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda509.pdbqt --out docked/hsg1_dbfda509.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda51.pdbqt --out docked/hsg1_dbfda51.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda510.pdbqt --out docked/hsg1_dbfda510.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda511.pdbqt --out docked/hsg1_dbfda511.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda512.pdbqt --out docked/hsg1_dbfda512.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda513.pdbqt --out docked/hsg1_dbfda513.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda514.pdbqt --out docked/hsg1_dbfda514.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda515.pdbqt --out docked/hsg1_dbfda515.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda516.pdbqt --out docked/hsg1_dbfda516.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda517.pdbqt --out docked/hsg1_dbfda517.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda518.pdbqt --out docked/hsg1_dbfda518.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda519.pdbqt --out docked/hsg1_dbfda519.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda52.pdbqt --out docked/hsg1_dbfda52.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda520.pdbqt --out docked/hsg1_dbfda520.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda521.pdbqt --out docked/hsg1_dbfda521.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda522.pdbqt --out docked/hsg1_dbfda522.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda523.pdbqt --out docked/hsg1_dbfda523.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda524.pdbqt --out docked/hsg1_dbfda524.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda525.pdbqt --out docked/hsg1_dbfda525.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda526.pdbqt --out docked/hsg1_dbfda526.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda527.pdbqt --out docked/hsg1_dbfda527.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda528.pdbqt --out docked/hsg1_dbfda528.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda529.pdbqt --out docked/hsg1_dbfda529.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda53.pdbqt --out docked/hsg1_dbfda53.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda530.pdbqt --out docked/hsg1_dbfda530.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda531.pdbqt --out docked/hsg1_dbfda531.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda532.pdbqt --out docked/hsg1_dbfda532.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda533.pdbqt --out docked/hsg1_dbfda533.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda534.pdbqt --out docked/hsg1_dbfda534.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda535.pdbqt --out docked/hsg1_dbfda535.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda536.pdbqt --out docked/hsg1_dbfda536.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda537.pdbqt --out docked/hsg1_dbfda537.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda538.pdbqt --out docked/hsg1_dbfda538.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda539.pdbqt --out docked/hsg1_dbfda539.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda54.pdbqt --out docked/hsg1_dbfda54.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda540.pdbqt --out docked/hsg1_dbfda540.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda541.pdbqt --out docked/hsg1_dbfda541.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda542.pdbqt --out docked/hsg1_dbfda542.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda543.pdbqt --out docked/hsg1_dbfda543.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda544.pdbqt --out docked/hsg1_dbfda544.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda545.pdbqt --out docked/hsg1_dbfda545.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda546.pdbqt --out docked/hsg1_dbfda546.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda547.pdbqt --out docked/hsg1_dbfda547.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda548.pdbqt --out docked/hsg1_dbfda548.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda549.pdbqt --out docked/hsg1_dbfda549.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda55.pdbqt --out docked/hsg1_dbfda55.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda550.pdbqt --out docked/hsg1_dbfda550.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda551.pdbqt --out docked/hsg1_dbfda551.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda552.pdbqt --out docked/hsg1_dbfda552.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda553.pdbqt --out docked/hsg1_dbfda553.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda554.pdbqt --out docked/hsg1_dbfda554.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda555.pdbqt --out docked/hsg1_dbfda555.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda556.pdbqt --out docked/hsg1_dbfda556.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda557.pdbqt --out docked/hsg1_dbfda557.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda558.pdbqt --out docked/hsg1_dbfda558.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda559.pdbqt --out docked/hsg1_dbfda559.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda56.pdbqt --out docked/hsg1_dbfda56.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda560.pdbqt --out docked/hsg1_dbfda560.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda561.pdbqt --out docked/hsg1_dbfda561.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda562.pdbqt --out docked/hsg1_dbfda562.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda563.pdbqt --out docked/hsg1_dbfda563.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda564.pdbqt --out docked/hsg1_dbfda564.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda565.pdbqt --out docked/hsg1_dbfda565.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda566.pdbqt --out docked/hsg1_dbfda566.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda567.pdbqt --out docked/hsg1_dbfda567.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda568.pdbqt --out docked/hsg1_dbfda568.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda569.pdbqt --out docked/hsg1_dbfda569.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda57.pdbqt --out docked/hsg1_dbfda57.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda570.pdbqt --out docked/hsg1_dbfda570.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda571.pdbqt --out docked/hsg1_dbfda571.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda572.pdbqt --out docked/hsg1_dbfda572.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda573.pdbqt --out docked/hsg1_dbfda573.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda574.pdbqt --out docked/hsg1_dbfda574.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda575.pdbqt --out docked/hsg1_dbfda575.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda576.pdbqt --out docked/hsg1_dbfda576.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda577.pdbqt --out docked/hsg1_dbfda577.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda578.pdbqt --out docked/hsg1_dbfda578.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda579.pdbqt --out docked/hsg1_dbfda579.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda58.pdbqt --out docked/hsg1_dbfda58.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda580.pdbqt --out docked/hsg1_dbfda580.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda581.pdbqt --out docked/hsg1_dbfda581.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda582.pdbqt --out docked/hsg1_dbfda582.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda583.pdbqt --out docked/hsg1_dbfda583.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda584.pdbqt --out docked/hsg1_dbfda584.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda585.pdbqt --out docked/hsg1_dbfda585.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda586.pdbqt --out docked/hsg1_dbfda586.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda587.pdbqt --out docked/hsg1_dbfda587.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda588.pdbqt --out docked/hsg1_dbfda588.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda589.pdbqt --out docked/hsg1_dbfda589.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda59.pdbqt --out docked/hsg1_dbfda59.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda590.pdbqt --out docked/hsg1_dbfda590.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda591.pdbqt --out docked/hsg1_dbfda591.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda592.pdbqt --out docked/hsg1_dbfda592.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda593.pdbqt --out docked/hsg1_dbfda593.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda594.pdbqt --out docked/hsg1_dbfda594.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda595.pdbqt --out docked/hsg1_dbfda595.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda596.pdbqt --out docked/hsg1_dbfda596.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda597.pdbqt --out docked/hsg1_dbfda597.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda598.pdbqt --out docked/hsg1_dbfda598.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda599.pdbqt --out docked/hsg1_dbfda599.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda6.pdbqt --out docked/hsg1_dbfda6.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda60.pdbqt --out docked/hsg1_dbfda60.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda600.pdbqt --out docked/hsg1_dbfda600.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda601.pdbqt --out docked/hsg1_dbfda601.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda602.pdbqt --out docked/hsg1_dbfda602.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda603.pdbqt --out docked/hsg1_dbfda603.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda604.pdbqt --out docked/hsg1_dbfda604.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda605.pdbqt --out docked/hsg1_dbfda605.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda606.pdbqt --out docked/hsg1_dbfda606.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda607.pdbqt --out docked/hsg1_dbfda607.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda608.pdbqt --out docked/hsg1_dbfda608.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda609.pdbqt --out docked/hsg1_dbfda609.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda61.pdbqt --out docked/hsg1_dbfda61.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda610.pdbqt --out docked/hsg1_dbfda610.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda611.pdbqt --out docked/hsg1_dbfda611.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda612.pdbqt --out docked/hsg1_dbfda612.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda613.pdbqt --out docked/hsg1_dbfda613.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda614.pdbqt --out docked/hsg1_dbfda614.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda615.pdbqt --out docked/hsg1_dbfda615.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda616.pdbqt --out docked/hsg1_dbfda616.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda617.pdbqt --out docked/hsg1_dbfda617.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda618.pdbqt --out docked/hsg1_dbfda618.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda619.pdbqt --out docked/hsg1_dbfda619.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda62.pdbqt --out docked/hsg1_dbfda62.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda620.pdbqt --out docked/hsg1_dbfda620.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda621.pdbqt --out docked/hsg1_dbfda621.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda622.pdbqt --out docked/hsg1_dbfda622.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda623.pdbqt --out docked/hsg1_dbfda623.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda624.pdbqt --out docked/hsg1_dbfda624.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda625.pdbqt --out docked/hsg1_dbfda625.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda626.pdbqt --out docked/hsg1_dbfda626.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda627.pdbqt --out docked/hsg1_dbfda627.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda628.pdbqt --out docked/hsg1_dbfda628.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda629.pdbqt --out docked/hsg1_dbfda629.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda63.pdbqt --out docked/hsg1_dbfda63.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda630.pdbqt --out docked/hsg1_dbfda630.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda631.pdbqt --out docked/hsg1_dbfda631.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda632.pdbqt --out docked/hsg1_dbfda632.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda633.pdbqt --out docked/hsg1_dbfda633.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda634.pdbqt --out docked/hsg1_dbfda634.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda635.pdbqt --out docked/hsg1_dbfda635.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda636.pdbqt --out docked/hsg1_dbfda636.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda637.pdbqt --out docked/hsg1_dbfda637.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda638.pdbqt --out docked/hsg1_dbfda638.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda639.pdbqt --out docked/hsg1_dbfda639.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda64.pdbqt --out docked/hsg1_dbfda64.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda640.pdbqt --out docked/hsg1_dbfda640.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda641.pdbqt --out docked/hsg1_dbfda641.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda642.pdbqt --out docked/hsg1_dbfda642.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda643.pdbqt --out docked/hsg1_dbfda643.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda644.pdbqt --out docked/hsg1_dbfda644.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda645.pdbqt --out docked/hsg1_dbfda645.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda646.pdbqt --out docked/hsg1_dbfda646.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda647.pdbqt --out docked/hsg1_dbfda647.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda648.pdbqt --out docked/hsg1_dbfda648.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda649.pdbqt --out docked/hsg1_dbfda649.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda65.pdbqt --out docked/hsg1_dbfda65.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda650.pdbqt --out docked/hsg1_dbfda650.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda651.pdbqt --out docked/hsg1_dbfda651.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda652.pdbqt --out docked/hsg1_dbfda652.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda653.pdbqt --out docked/hsg1_dbfda653.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda654.pdbqt --out docked/hsg1_dbfda654.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda655.pdbqt --out docked/hsg1_dbfda655.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda656.pdbqt --out docked/hsg1_dbfda656.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda657.pdbqt --out docked/hsg1_dbfda657.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda658.pdbqt --out docked/hsg1_dbfda658.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda659.pdbqt --out docked/hsg1_dbfda659.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda66.pdbqt --out docked/hsg1_dbfda66.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda660.pdbqt --out docked/hsg1_dbfda660.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda661.pdbqt --out docked/hsg1_dbfda661.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda662.pdbqt --out docked/hsg1_dbfda662.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda663.pdbqt --out docked/hsg1_dbfda663.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda664.pdbqt --out docked/hsg1_dbfda664.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda665.pdbqt --out docked/hsg1_dbfda665.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda666.pdbqt --out docked/hsg1_dbfda666.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda667.pdbqt --out docked/hsg1_dbfda667.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda668.pdbqt --out docked/hsg1_dbfda668.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda669.pdbqt --out docked/hsg1_dbfda669.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda67.pdbqt --out docked/hsg1_dbfda67.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda670.pdbqt --out docked/hsg1_dbfda670.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda671.pdbqt --out docked/hsg1_dbfda671.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda672.pdbqt --out docked/hsg1_dbfda672.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda673.pdbqt --out docked/hsg1_dbfda673.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda674.pdbqt --out docked/hsg1_dbfda674.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda675.pdbqt --out docked/hsg1_dbfda675.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda676.pdbqt --out docked/hsg1_dbfda676.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda677.pdbqt --out docked/hsg1_dbfda677.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda678.pdbqt --out docked/hsg1_dbfda678.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda679.pdbqt --out docked/hsg1_dbfda679.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda68.pdbqt --out docked/hsg1_dbfda68.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda680.pdbqt --out docked/hsg1_dbfda680.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda681.pdbqt --out docked/hsg1_dbfda681.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda682.pdbqt --out docked/hsg1_dbfda682.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda683.pdbqt --out docked/hsg1_dbfda683.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda684.pdbqt --out docked/hsg1_dbfda684.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda685.pdbqt --out docked/hsg1_dbfda685.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda686.pdbqt --out docked/hsg1_dbfda686.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda687.pdbqt --out docked/hsg1_dbfda687.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda688.pdbqt --out docked/hsg1_dbfda688.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda689.pdbqt --out docked/hsg1_dbfda689.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda69.pdbqt --out docked/hsg1_dbfda69.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda690.pdbqt --out docked/hsg1_dbfda690.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda691.pdbqt --out docked/hsg1_dbfda691.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda692.pdbqt --out docked/hsg1_dbfda692.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda693.pdbqt --out docked/hsg1_dbfda693.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda694.pdbqt --out docked/hsg1_dbfda694.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda695.pdbqt --out docked/hsg1_dbfda695.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda696.pdbqt --out docked/hsg1_dbfda696.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda697.pdbqt --out docked/hsg1_dbfda697.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda698.pdbqt --out docked/hsg1_dbfda698.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda699.pdbqt --out docked/hsg1_dbfda699.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda7.pdbqt --out docked/hsg1_dbfda7.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda70.pdbqt --out docked/hsg1_dbfda70.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda700.pdbqt --out docked/hsg1_dbfda700.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda701.pdbqt --out docked/hsg1_dbfda701.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda702.pdbqt --out docked/hsg1_dbfda702.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda703.pdbqt --out docked/hsg1_dbfda703.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda704.pdbqt --out docked/hsg1_dbfda704.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda705.pdbqt --out docked/hsg1_dbfda705.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda706.pdbqt --out docked/hsg1_dbfda706.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda707.pdbqt --out docked/hsg1_dbfda707.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda708.pdbqt --out docked/hsg1_dbfda708.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda709.pdbqt --out docked/hsg1_dbfda709.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda71.pdbqt --out docked/hsg1_dbfda71.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda710.pdbqt --out docked/hsg1_dbfda710.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda711.pdbqt --out docked/hsg1_dbfda711.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda712.pdbqt --out docked/hsg1_dbfda712.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda713.pdbqt --out docked/hsg1_dbfda713.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda714.pdbqt --out docked/hsg1_dbfda714.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda715.pdbqt --out docked/hsg1_dbfda715.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda716.pdbqt --out docked/hsg1_dbfda716.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda717.pdbqt --out docked/hsg1_dbfda717.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda718.pdbqt --out docked/hsg1_dbfda718.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda719.pdbqt --out docked/hsg1_dbfda719.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda72.pdbqt --out docked/hsg1_dbfda72.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda720.pdbqt --out docked/hsg1_dbfda720.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda721.pdbqt --out docked/hsg1_dbfda721.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda722.pdbqt --out docked/hsg1_dbfda722.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda723.pdbqt --out docked/hsg1_dbfda723.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda724.pdbqt --out docked/hsg1_dbfda724.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda725.pdbqt --out docked/hsg1_dbfda725.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda726.pdbqt --out docked/hsg1_dbfda726.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda727.pdbqt --out docked/hsg1_dbfda727.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda728.pdbqt --out docked/hsg1_dbfda728.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda729.pdbqt --out docked/hsg1_dbfda729.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda73.pdbqt --out docked/hsg1_dbfda73.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda730.pdbqt --out docked/hsg1_dbfda730.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda731.pdbqt --out docked/hsg1_dbfda731.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda732.pdbqt --out docked/hsg1_dbfda732.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda733.pdbqt --out docked/hsg1_dbfda733.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda734.pdbqt --out docked/hsg1_dbfda734.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda735.pdbqt --out docked/hsg1_dbfda735.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda736.pdbqt --out docked/hsg1_dbfda736.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda737.pdbqt --out docked/hsg1_dbfda737.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda738.pdbqt --out docked/hsg1_dbfda738.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda739.pdbqt --out docked/hsg1_dbfda739.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda74.pdbqt --out docked/hsg1_dbfda74.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda740.pdbqt --out docked/hsg1_dbfda740.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda741.pdbqt --out docked/hsg1_dbfda741.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda742.pdbqt --out docked/hsg1_dbfda742.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda743.pdbqt --out docked/hsg1_dbfda743.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda744.pdbqt --out docked/hsg1_dbfda744.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda745.pdbqt --out docked/hsg1_dbfda745.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda746.pdbqt --out docked/hsg1_dbfda746.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda747.pdbqt --out docked/hsg1_dbfda747.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda748.pdbqt --out docked/hsg1_dbfda748.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda749.pdbqt --out docked/hsg1_dbfda749.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda75.pdbqt --out docked/hsg1_dbfda75.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda750.pdbqt --out docked/hsg1_dbfda750.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda751.pdbqt --out docked/hsg1_dbfda751.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda752.pdbqt --out docked/hsg1_dbfda752.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda753.pdbqt --out docked/hsg1_dbfda753.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda754.pdbqt --out docked/hsg1_dbfda754.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda755.pdbqt --out docked/hsg1_dbfda755.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda756.pdbqt --out docked/hsg1_dbfda756.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda757.pdbqt --out docked/hsg1_dbfda757.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda758.pdbqt --out docked/hsg1_dbfda758.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda759.pdbqt --out docked/hsg1_dbfda759.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda76.pdbqt --out docked/hsg1_dbfda76.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda760.pdbqt --out docked/hsg1_dbfda760.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda761.pdbqt --out docked/hsg1_dbfda761.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda762.pdbqt --out docked/hsg1_dbfda762.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda763.pdbqt --out docked/hsg1_dbfda763.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda764.pdbqt --out docked/hsg1_dbfda764.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda765.pdbqt --out docked/hsg1_dbfda765.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda766.pdbqt --out docked/hsg1_dbfda766.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda767.pdbqt --out docked/hsg1_dbfda767.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda768.pdbqt --out docked/hsg1_dbfda768.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda769.pdbqt --out docked/hsg1_dbfda769.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda77.pdbqt --out docked/hsg1_dbfda77.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda770.pdbqt --out docked/hsg1_dbfda770.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda771.pdbqt --out docked/hsg1_dbfda771.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda772.pdbqt --out docked/hsg1_dbfda772.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda773.pdbqt --out docked/hsg1_dbfda773.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda774.pdbqt --out docked/hsg1_dbfda774.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda775.pdbqt --out docked/hsg1_dbfda775.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda776.pdbqt --out docked/hsg1_dbfda776.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda777.pdbqt --out docked/hsg1_dbfda777.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda778.pdbqt --out docked/hsg1_dbfda778.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda779.pdbqt --out docked/hsg1_dbfda779.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda78.pdbqt --out docked/hsg1_dbfda78.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda780.pdbqt --out docked/hsg1_dbfda780.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda781.pdbqt --out docked/hsg1_dbfda781.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda782.pdbqt --out docked/hsg1_dbfda782.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda783.pdbqt --out docked/hsg1_dbfda783.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda784.pdbqt --out docked/hsg1_dbfda784.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda785.pdbqt --out docked/hsg1_dbfda785.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda786.pdbqt --out docked/hsg1_dbfda786.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda787.pdbqt --out docked/hsg1_dbfda787.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda788.pdbqt --out docked/hsg1_dbfda788.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda789.pdbqt --out docked/hsg1_dbfda789.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda79.pdbqt --out docked/hsg1_dbfda79.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda790.pdbqt --out docked/hsg1_dbfda790.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda791.pdbqt --out docked/hsg1_dbfda791.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda792.pdbqt --out docked/hsg1_dbfda792.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda793.pdbqt --out docked/hsg1_dbfda793.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda794.pdbqt --out docked/hsg1_dbfda794.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda795.pdbqt --out docked/hsg1_dbfda795.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda796.pdbqt --out docked/hsg1_dbfda796.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda797.pdbqt --out docked/hsg1_dbfda797.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda798.pdbqt --out docked/hsg1_dbfda798.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda799.pdbqt --out docked/hsg1_dbfda799.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda8.pdbqt --out docked/hsg1_dbfda8.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda80.pdbqt --out docked/hsg1_dbfda80.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda800.pdbqt --out docked/hsg1_dbfda800.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda801.pdbqt --out docked/hsg1_dbfda801.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda802.pdbqt --out docked/hsg1_dbfda802.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda803.pdbqt --out docked/hsg1_dbfda803.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda804.pdbqt --out docked/hsg1_dbfda804.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda805.pdbqt --out docked/hsg1_dbfda805.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda806.pdbqt --out docked/hsg1_dbfda806.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda807.pdbqt --out docked/hsg1_dbfda807.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda808.pdbqt --out docked/hsg1_dbfda808.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda809.pdbqt --out docked/hsg1_dbfda809.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda81.pdbqt --out docked/hsg1_dbfda81.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda810.pdbqt --out docked/hsg1_dbfda810.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda811.pdbqt --out docked/hsg1_dbfda811.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda812.pdbqt --out docked/hsg1_dbfda812.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda813.pdbqt --out docked/hsg1_dbfda813.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda814.pdbqt --out docked/hsg1_dbfda814.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda815.pdbqt --out docked/hsg1_dbfda815.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda816.pdbqt --out docked/hsg1_dbfda816.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda817.pdbqt --out docked/hsg1_dbfda817.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda818.pdbqt --out docked/hsg1_dbfda818.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda819.pdbqt --out docked/hsg1_dbfda819.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda82.pdbqt --out docked/hsg1_dbfda82.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda820.pdbqt --out docked/hsg1_dbfda820.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda821.pdbqt --out docked/hsg1_dbfda821.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda822.pdbqt --out docked/hsg1_dbfda822.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda823.pdbqt --out docked/hsg1_dbfda823.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda824.pdbqt --out docked/hsg1_dbfda824.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda825.pdbqt --out docked/hsg1_dbfda825.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda826.pdbqt --out docked/hsg1_dbfda826.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda827.pdbqt --out docked/hsg1_dbfda827.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda828.pdbqt --out docked/hsg1_dbfda828.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda829.pdbqt --out docked/hsg1_dbfda829.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda83.pdbqt --out docked/hsg1_dbfda83.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda830.pdbqt --out docked/hsg1_dbfda830.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda831.pdbqt --out docked/hsg1_dbfda831.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda832.pdbqt --out docked/hsg1_dbfda832.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda833.pdbqt --out docked/hsg1_dbfda833.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda834.pdbqt --out docked/hsg1_dbfda834.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda835.pdbqt --out docked/hsg1_dbfda835.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda836.pdbqt --out docked/hsg1_dbfda836.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda837.pdbqt --out docked/hsg1_dbfda837.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda838.pdbqt --out docked/hsg1_dbfda838.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda839.pdbqt --out docked/hsg1_dbfda839.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda84.pdbqt --out docked/hsg1_dbfda84.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda840.pdbqt --out docked/hsg1_dbfda840.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda841.pdbqt --out docked/hsg1_dbfda841.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda842.pdbqt --out docked/hsg1_dbfda842.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda843.pdbqt --out docked/hsg1_dbfda843.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda844.pdbqt --out docked/hsg1_dbfda844.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda845.pdbqt --out docked/hsg1_dbfda845.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda846.pdbqt --out docked/hsg1_dbfda846.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda847.pdbqt --out docked/hsg1_dbfda847.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda848.pdbqt --out docked/hsg1_dbfda848.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda849.pdbqt --out docked/hsg1_dbfda849.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda85.pdbqt --out docked/hsg1_dbfda85.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda850.pdbqt --out docked/hsg1_dbfda850.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda851.pdbqt --out docked/hsg1_dbfda851.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda852.pdbqt --out docked/hsg1_dbfda852.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda853.pdbqt --out docked/hsg1_dbfda853.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda854.pdbqt --out docked/hsg1_dbfda854.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda855.pdbqt --out docked/hsg1_dbfda855.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda856.pdbqt --out docked/hsg1_dbfda856.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda857.pdbqt --out docked/hsg1_dbfda857.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda858.pdbqt --out docked/hsg1_dbfda858.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda859.pdbqt --out docked/hsg1_dbfda859.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda86.pdbqt --out docked/hsg1_dbfda86.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda860.pdbqt --out docked/hsg1_dbfda860.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda861.pdbqt --out docked/hsg1_dbfda861.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda862.pdbqt --out docked/hsg1_dbfda862.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda863.pdbqt --out docked/hsg1_dbfda863.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda864.pdbqt --out docked/hsg1_dbfda864.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda865.pdbqt --out docked/hsg1_dbfda865.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda866.pdbqt --out docked/hsg1_dbfda866.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda867.pdbqt --out docked/hsg1_dbfda867.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda868.pdbqt --out docked/hsg1_dbfda868.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda869.pdbqt --out docked/hsg1_dbfda869.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda87.pdbqt --out docked/hsg1_dbfda87.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda870.pdbqt --out docked/hsg1_dbfda870.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda871.pdbqt --out docked/hsg1_dbfda871.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda872.pdbqt --out docked/hsg1_dbfda872.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda873.pdbqt --out docked/hsg1_dbfda873.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda874.pdbqt --out docked/hsg1_dbfda874.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda875.pdbqt --out docked/hsg1_dbfda875.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda876.pdbqt --out docked/hsg1_dbfda876.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda877.pdbqt --out docked/hsg1_dbfda877.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda878.pdbqt --out docked/hsg1_dbfda878.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda879.pdbqt --out docked/hsg1_dbfda879.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda88.pdbqt --out docked/hsg1_dbfda88.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda880.pdbqt --out docked/hsg1_dbfda880.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda881.pdbqt --out docked/hsg1_dbfda881.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda882.pdbqt --out docked/hsg1_dbfda882.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda883.pdbqt --out docked/hsg1_dbfda883.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda884.pdbqt --out docked/hsg1_dbfda884.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda885.pdbqt --out docked/hsg1_dbfda885.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda886.pdbqt --out docked/hsg1_dbfda886.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda887.pdbqt --out docked/hsg1_dbfda887.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda888.pdbqt --out docked/hsg1_dbfda888.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda889.pdbqt --out docked/hsg1_dbfda889.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda89.pdbqt --out docked/hsg1_dbfda89.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda890.pdbqt --out docked/hsg1_dbfda890.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda891.pdbqt --out docked/hsg1_dbfda891.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda892.pdbqt --out docked/hsg1_dbfda892.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda893.pdbqt --out docked/hsg1_dbfda893.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda894.pdbqt --out docked/hsg1_dbfda894.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda895.pdbqt --out docked/hsg1_dbfda895.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda896.pdbqt --out docked/hsg1_dbfda896.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda897.pdbqt --out docked/hsg1_dbfda897.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda898.pdbqt --out docked/hsg1_dbfda898.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda899.pdbqt --out docked/hsg1_dbfda899.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda9.pdbqt --out docked/hsg1_dbfda9.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda90.pdbqt --out docked/hsg1_dbfda90.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda900.pdbqt --out docked/hsg1_dbfda900.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda901.pdbqt --out docked/hsg1_dbfda901.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda902.pdbqt --out docked/hsg1_dbfda902.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda903.pdbqt --out docked/hsg1_dbfda903.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda904.pdbqt --out docked/hsg1_dbfda904.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda905.pdbqt --out docked/hsg1_dbfda905.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda906.pdbqt --out docked/hsg1_dbfda906.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda907.pdbqt --out docked/hsg1_dbfda907.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda908.pdbqt --out docked/hsg1_dbfda908.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda909.pdbqt --out docked/hsg1_dbfda909.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda91.pdbqt --out docked/hsg1_dbfda91.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda910.pdbqt --out docked/hsg1_dbfda910.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda911.pdbqt --out docked/hsg1_dbfda911.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda912.pdbqt --out docked/hsg1_dbfda912.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda913.pdbqt --out docked/hsg1_dbfda913.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda914.pdbqt --out docked/hsg1_dbfda914.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda915.pdbqt --out docked/hsg1_dbfda915.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda916.pdbqt --out docked/hsg1_dbfda916.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda917.pdbqt --out docked/hsg1_dbfda917.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda918.pdbqt --out docked/hsg1_dbfda918.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda919.pdbqt --out docked/hsg1_dbfda919.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda92.pdbqt --out docked/hsg1_dbfda92.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda920.pdbqt --out docked/hsg1_dbfda920.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda921.pdbqt --out docked/hsg1_dbfda921.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda922.pdbqt --out docked/hsg1_dbfda922.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda923.pdbqt --out docked/hsg1_dbfda923.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda924.pdbqt --out docked/hsg1_dbfda924.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda925.pdbqt --out docked/hsg1_dbfda925.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda926.pdbqt --out docked/hsg1_dbfda926.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda927.pdbqt --out docked/hsg1_dbfda927.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda928.pdbqt --out docked/hsg1_dbfda928.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda929.pdbqt --out docked/hsg1_dbfda929.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda93.pdbqt --out docked/hsg1_dbfda93.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda930.pdbqt --out docked/hsg1_dbfda930.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda931.pdbqt --out docked/hsg1_dbfda931.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda932.pdbqt --out docked/hsg1_dbfda932.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda933.pdbqt --out docked/hsg1_dbfda933.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda934.pdbqt --out docked/hsg1_dbfda934.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda935.pdbqt --out docked/hsg1_dbfda935.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda936.pdbqt --out docked/hsg1_dbfda936.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda937.pdbqt --out docked/hsg1_dbfda937.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda938.pdbqt --out docked/hsg1_dbfda938.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda939.pdbqt --out docked/hsg1_dbfda939.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda94.pdbqt --out docked/hsg1_dbfda94.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda940.pdbqt --out docked/hsg1_dbfda940.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda941.pdbqt --out docked/hsg1_dbfda941.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda942.pdbqt --out docked/hsg1_dbfda942.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda943.pdbqt --out docked/hsg1_dbfda943.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda944.pdbqt --out docked/hsg1_dbfda944.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda945.pdbqt --out docked/hsg1_dbfda945.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda946.pdbqt --out docked/hsg1_dbfda946.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda947.pdbqt --out docked/hsg1_dbfda947.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda948.pdbqt --out docked/hsg1_dbfda948.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda949.pdbqt --out docked/hsg1_dbfda949.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda95.pdbqt --out docked/hsg1_dbfda95.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda950.pdbqt --out docked/hsg1_dbfda950.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda951.pdbqt --out docked/hsg1_dbfda951.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda952.pdbqt --out docked/hsg1_dbfda952.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda953.pdbqt --out docked/hsg1_dbfda953.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda954.pdbqt --out docked/hsg1_dbfda954.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda955.pdbqt --out docked/hsg1_dbfda955.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda956.pdbqt --out docked/hsg1_dbfda956.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda957.pdbqt --out docked/hsg1_dbfda957.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda958.pdbqt --out docked/hsg1_dbfda958.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda959.pdbqt --out docked/hsg1_dbfda959.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda96.pdbqt --out docked/hsg1_dbfda96.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda960.pdbqt --out docked/hsg1_dbfda960.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda961.pdbqt --out docked/hsg1_dbfda961.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda962.pdbqt --out docked/hsg1_dbfda962.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda963.pdbqt --out docked/hsg1_dbfda963.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda964.pdbqt --out docked/hsg1_dbfda964.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda965.pdbqt --out docked/hsg1_dbfda965.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda966.pdbqt --out docked/hsg1_dbfda966.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda967.pdbqt --out docked/hsg1_dbfda967.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda968.pdbqt --out docked/hsg1_dbfda968.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda969.pdbqt --out docked/hsg1_dbfda969.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda97.pdbqt --out docked/hsg1_dbfda97.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda970.pdbqt --out docked/hsg1_dbfda970.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda971.pdbqt --out docked/hsg1_dbfda971.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda972.pdbqt --out docked/hsg1_dbfda972.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda973.pdbqt --out docked/hsg1_dbfda973.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda974.pdbqt --out docked/hsg1_dbfda974.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda975.pdbqt --out docked/hsg1_dbfda975.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda976.pdbqt --out docked/hsg1_dbfda976.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda977.pdbqt --out docked/hsg1_dbfda977.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda978.pdbqt --out docked/hsg1_dbfda978.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda979.pdbqt --out docked/hsg1_dbfda979.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda98.pdbqt --out docked/hsg1_dbfda98.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda980.pdbqt --out docked/hsg1_dbfda980.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda981.pdbqt --out docked/hsg1_dbfda981.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda982.pdbqt --out docked/hsg1_dbfda982.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda983.pdbqt --out docked/hsg1_dbfda983.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda984.pdbqt --out docked/hsg1_dbfda984.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda985.pdbqt --out docked/hsg1_dbfda985.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda986.pdbqt --out docked/hsg1_dbfda986.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda987.pdbqt --out docked/hsg1_dbfda987.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda988.pdbqt --out docked/hsg1_dbfda988.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda989.pdbqt --out docked/hsg1_dbfda989.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda99.pdbqt --out docked/hsg1_dbfda99.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda990.pdbqt --out docked/hsg1_dbfda990.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda991.pdbqt --out docked/hsg1_dbfda991.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda992.pdbqt --out docked/hsg1_dbfda992.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda993.pdbqt --out docked/hsg1_dbfda993.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda994.pdbqt --out docked/hsg1_dbfda994.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda995.pdbqt --out docked/hsg1_dbfda995.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda996.pdbqt --out docked/hsg1_dbfda996.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda997.pdbqt --out docked/hsg1_dbfda997.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda998.pdbqt --out docked/hsg1_dbfda998.pdbqt --cpu 14
vina --config config.txt --receptor hsg1.pdbqt --ligand library/dbfda999.pdbqt --out docked/hsg1_dbfda999.pdbqt --cpu 14
