#!/bin/bash
#SBATCH -N 1
#SBATCH -p GPU-shared
#SBATCH --ntasks-per-node 1
#SBATCH --gres=gpu:p100:1
#SBATCH -t 48:00:00

#echo commands to stdout
set -x

# Set up the environment
source ~/.bashrc
module load anaconda3
conda activate openmm

# Run MD
cd /pylon5/mc4s8bp/dminh/3cl-pro/YANK/ligands/1-equilibrate
python ./run_equilibration.py --system_name ../0-build/ZINC000013985228_solv --simulation_time 5
