#PBS -S /bin/bash
#PBS -o ZINC000001542916_solv.out
#PBS -e ZINC000001542916_solv.err
#PBS -q cuda
#PBS -W x=GRES:gpus@1
#PBS -l nodes=compute-1-8:ppn=1:gpus,walltime=168:00:00
#PBS -r y

export CUDA_VISIBLE_DEVICES=1

echo Running on compute-1-0, targeting device 1

source ~/.bashrc
module load miniconda/3
conda activate openmm

# Run MD
cd /home/dminh/3cl-pro/YANK/ligands/1-equilibrate
python ./run_equilibration.py --system_name ../0-build/ZINC000001542916_solv --simulation_time 5
